### ISSUE TITLE
关于抗干扰能力

### ISSUE THREAD

**Issue by qazzombie** [jiabaocui/MIAIS#1]
您好 ，请问您训练过程有加入干扰层进行训练吗，还是论文上的图片就是加入干扰层训练得到的结果？

**Comment by jiabaocui** [comment]
您好！
我们在训练的时候，加入了模拟干扰层，具体噪声形式见文件 ./utils/AFD_config.py Line 64:
"noise = 'cropout((0.85, 1.),(0.85, 1.))+dropout(0.7, 1.)+jpeg()'". 
感谢您对我们工作的关注。

**Comment by qazzombie** [comment]
> 

你好，那你们这个结果抗干扰，大概能抵抗的压缩系数范围是多少呀

**Comment by qazzombie** [comment]
> 您好！ 我们在训练的时候，加入了模拟干扰层，具体噪声形式见文件 ./utils/AFD_config.py Line 64: "noise = 'cropout((0.85, 1.),(0.85, 1.))+dropout(0.7, 1.)+jpeg()'". 感谢您对我们工作的关注。
那你们这个结果抗干扰，大概能抵抗的压缩系数范围是多少呀

**Comment by jiabaocui** [comment]
> 
这个我们没有测试，也不属于该文章的实验范畴。如果对噪声感兴趣，建议阅读这一篇文章“HiDDeN: Hiding Data With Deep Networks”，里面有比较详细的介绍和实验。

**Comment by qazzombie** [comment]
> > 
> 
> 这个我们没有测试，也不属于该文章的实验范畴。如果对噪声感兴趣，建议阅读这一篇文章“HiDDeN: Hiding Data With Deep Networks”，里面有比较详细的介绍和实验。

好的，感谢，这个文章已经读过了，哈哈哈，我就是想看看别人实际训练出来的效果怎么样，和我自己的做对比
