### ISSUE TITLE
I want some help to replicate the code

### ISSUE THREAD

**Issue by recardowang** [jiabaocui/MIAIS#2]
These days I read your papers in IEEE Transactions on Image Processing, I was so confused when I am trying to replicate the code, I have already download all the datas and modify some of the routes, but every time I run the code, its will always exists the problem '/mnt/data2/pengyi/encryption/cover'. I have read the code over and over again, but I still can't find the ways to solve it. I was a junior college student in Wuhan University, it was too hard for me to solve the problem, but I was attracted by its thoughts and chose it as my final experiments, I really want to replicate the code. Even if I have tried my best, I still can't work it out, and I can't find your email in the paper, so I'm here to ask you for some help. If you could help I will be very grateful.

**Comment by jiabaocui** [comment]
This route “'/mnt/data2/pengyi/encryption/cover'” is just the cover image saved path. For first runing, you should copy the cover image into the above path. If there are still some questions, please do not hesitate to connect me for the following email: jbcui@zju.edu.cn.
